FROM debian:12
ARG USER

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    apt-utils \
    curl \
    git

RUN adduser --disabled-password -gecos "" ${USER}
COPY --chown=${USER}:${USER} . /home/${USER}/.homerepo
