FROM debian:12
ARG USER
ARG UID

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    apt-utils \
    curl \
    git \
    sudo

RUN adduser --uid ${UID} --disabled-password --comment "" ${USER} && \
    usermod -aG sudo ${USER} && \
    sed -i '/^%sudo/s/ALL$/NOPASSWD:ALL/' /etc/sudoers

